### PR TITLE
Add generic libvirt connection plugin

### PR DESCRIPTION
**Pull request by odyssey4me**
##### SUMMARY

Initial pass at libvirt/qemu connection plugin

Fixes: #12 

##### ISSUE TYPE

- Feature Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by daveol** [comment]
Should this not be named libvirt_qemu? Since it is only compatble with the qemu guest agent at the moment...

**Comment by odyssey4me** [comment]
@daveol I can do that. I think that's sensible. I'm hoping to extend its functionality, but time is a bit tight - so maybe it'd be better to rename it for now and once we have something else we can shift it over and leave an alias.

**Comment by odyssey4me** [comment]
@daveol Should I merge it as-is, then work on the additional remote URI functionality in a subsequent PR? What do you think? I'm thinking this may be useful as a base and I'd like to unblock any work you'd like to do on top of it.

**Comment by daveol** [comment]
@odyssey4me you can merge as-is if you want, the ```libvirt_lxc``` connection plugin would probably also need an update for supporting the remote URI functionality to keep it consistent (also an update to use the libvirt python api, but that's a different issue).

Then again it does not seem like a lot of work to implement the URI functionality for this plugin,  or am I wrong?

**Comment by odyssey4me** [comment]
@daveol I think I agree. While it's not a lot of work, I don't have enough time right now to dig into the details of it. So meh, I'll register an issue for it and we can move along. :)

**Pull request merged**
